Remove unused variable in revocations.c
During compile on macOS the default unused variable checking appears to be strict and found this.
```
revocations.c:259:12: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]
        u_int64_t i = 0;
                  ^
```